version: "3.9"

services:
  postgres:
    image: postgres
    env_file: ./envs/postgreSQL.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
      - ./configs/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/initdb.sh
    expose:
      - "5432"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}" ]

  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"

  main-react-ui:
    build: ./main-react-ui/.
    env_file: envs/main-react-ui.env
    expose:
      - "5173"
    volumes:
      - ./main-react-ui:/web
    command: bash -c "npm start"

  chats-react-ui:
    build: ./chats-react-ui/.
    env_file: ./envs/chats-react-ui.env
    expose:
      - "5174"
    volumes:
      - ./chats-react-ui:/web
    command: bash -c "npm start"

  auth-django:
    build: ./auth-django/.
    depends_on:
      - postgres
    env_file:
      - ./envs/django.env
      - ./envs/auth-django.env
      - ./envs/postgreSQL.env
    expose:
      - "8000"
    volumes:
      - ./auth-django:/app
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      "

  websockets-django:
    build: ./websockets-django/.
    env_file:
      - ./envs/django.env
      - ./envs/websockets-django.env
      - ./envs/postgreSQL.env
    depends_on:
      - postgres
    expose:
      - "8001"
    volumes:
      - ./websockets-django:/app
    links:
      - redis
    command: bash -c "
      python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8001
      "

  nginx:
    image: nginx
    depends_on:
      - auth-django
      #      - websockets-django
      - main-react-ui
      - chats-react-ui
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./auth-django/static_cdn:/home/static # Django Auth static files
      - ./auth-django/media_cdn:/home/static/media # Django Auth media files
      - ./websockets-django/static_cdn:/home/static # Django Websockets static files
      - ./websockets-django/media_cdn:/home/static/media # Django Websockets media files
      - ./main-react-ui:/var/www/main-react-ui # Main React UI
      - ./chats-react-ui:/var/www/chats-react-ui # Chats React UI
    ports:
      - "80:80"

volumes:
  pgdata:
