version: '3.9'

services:
  postgres:
    image: postgres:16.3
    env_file: ./envs/postgreSQL.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
      - ./configs/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/initdb.sh:ro
    expose:
      - '5432'
    ports:
      - '5432:5432'

  redis:
    image: redis:7.2.5
    expose:
      - '6379'

  main-angular-ui:
    build: ./microservices/main-angular-ui/.
    expose:
      - '4200'
    command: nginx -g 'daemon off;'

  chats-react-ui:
    build: ./microservices/chats-react-ui/.
    expose:
      - '5173'
    command: nginx -g 'daemon off;'

  auth-django:
    build: ./microservices/auth-django/.
    depends_on:
      - postgres
    env_file:
      - ./envs/django.env
      - ./envs/auth-django.env
      - ./envs/postgreSQL.env
    expose:
      - '8000'
    volumes:
      - ./microservices/auth-django:/app
    command: bash -c '
      ./wait-for-it.sh postgres:5432 -- python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000
      '

  websockets-django:
    build: ./microservices/websockets-django/.
    env_file:
      - ./envs/django.env
      - ./envs/websockets-django.env
      - ./envs/postgreSQL.env
    depends_on:
      - postgres
    expose:
      - '8001'
    volumes:
      - ./microservices/websockets-django:/app
    links:
      - redis
    command: bash -c '
      ./wait-for-it.sh postgres:5432 -- python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8001
      '

  nginx:
    image: nginx
    depends_on:
      - auth-django
      - websockets-django
      - main-angular-ui
      - chats-react-ui
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./microservices/auth-django/static_cdn:/home/static # Django Auth static files
      - ./microservices/auth-django/media_cdn:/home/static/media # Django Auth media files
      - ./microservices/websockets-django/static_cdn:/home/static # Django Websockets static files
      - ./microservices/websockets-django/media_cdn:/home/static/media # Django Websockets media files
    ports:
      - '80:80'

volumes:
  pgdata:
