version: '3.9'

services:
  postgres:
    image: postgres:16.3
    env_file: ./envs/postgreSQL.env
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
      - ./configs/postgres-entrypoint.sh:/docker-entrypoint-initdb.d/initdb.sh:ro
    ports:
      - '5432:5432'

  redis:
    image: redis:7.2.5
    ports:
      - '6379:6379'

volumes:
  pgdata:
